### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lucgovmw** [notoriousbdg/vrops-dashboard-snapshot_detail#1]
Hi Brandon , please see the image attached. I had this problem. And the name of the snapshot and the age of the snapshot was wrong. Customer did a snapshot with a customer name and the name was different in the view. The age was wrong too and no information about the creator as well and in the description was a description from Update Manager

**Comment by notoriousbdg** [comment]
Can you post the screenshot?  Also, check the object's properties on that specific snapshot instance in vROps to see if it's wrong there too.
