### ISSUE TITLE
Unable to collect snapshot metrics

### ISSUE THREAD

**Issue by jturnya** [notoriousbdg/vrops-dashboard-snapshot_detail#2]
Hi Brandon, 

I'm currently running vROps 7.0 but am having troubles with collecting metrics with your view/dashboard. If I try to run a report or generate a dashboard, I get nothing. Matter of fact my vROps cluster is generating anomaly alerts when I run a report with this view/metrics.

Do you have any suggestions? 

Thanks

**Comment by notoriousbdg** [comment]
The list will be empty if you don't have any VMs with snapshots.  If you know of a VM that has snapshots that should be on the list, check the all metrics tab to see if the snapshot metrics are collecting.

**Comment by a69rdstr** [comment]
I appear to be experiencing the same issue as "jtumya" above is having. I have a number of virtual machines with Snapshots on them but when I run or generate the provided report "All Snapshot Details" which is using the provided "Snapshot Detail" view I don't get any data back. If I try and preview the data in the "Snapshot Detail" view I get Preview is currently not available. If I click on any of Instance names in the "Snapshot Detail" view I get an error message "You must select a transformation for (whatever the instance name is) name". Above you mention "check the all metrics tab to see if the snapshot metrics are collecting" can you point where this is found in VROPs? I can't seem to locate where to check this at?

**Comment by notoriousbdg** [comment]
Find a VM in vROps that you know has a snapshot.  You should see the metrics for the snapshots at Disk Space|DATASTORENAME|Snapshot|SNAPSHOTINSTANCEID.

**Comment by a69rdstr** [comment]
If I look at a virtual machine that has a snapshot in VROPs under All Metrics, Disk Space I only see the following 3 metrics:
Guest File System stats|Total Guest File System Capacity (GB)
Guest File System stats|Total Guest File System Free (GB)
Guest File System stats|Total Guest File System Usage (%)
If I look in the All Metrics drop down for this virtual machine under Disk Space I see a few different Snap Shot metrics but nothing for SNAPSHOTINSTANCEID???
[Snapshot.docx](https://github.com/notoriousbdg/vrops-dashboard-snapshot_detail/files/3013175/Snapshot.docx)

**Comment by notoriousbdg** [comment]
Look for Disk Space under the All Metrics section.
