### ISSUE TITLE
Dashboard no information displayed

### ISSUE THREAD

**Issue by fordlynn2004** [notoriousbdg/vrops-dashboard-snapshot_detail#5]
HI Brandon

I follow your steps to import the snapshot dashboard.
but I don't see the VM snapshot information.

I confirmed that my virtual machine has a snapshot.

Is any other settings to be changed in vROps 7.5?
![2019-10-29_105644](https://user-images.githubusercontent.com/30993612/67734014-e7789f80-fa3a-11e9-8758-d5b7c6d6bdc6.jpg)

**Comment by notoriousbdg** [comment]
Sorry, I just noticed this issue.  Are you still having trouble?

**Comment by fordlynn2004** [comment]
NO
