### ISSUE TITLE
Creator and Description Column Fields Empty

### ISSUE THREAD

**Issue by amar9057** [notoriousbdg/vrops-dashboard-snapshot_detail#6]
Hey,

Good Day to you!!

I am also facing the same issue. Only creator and description columns fields are blank rest all are good.

What was the resolution adopted if this is solved. Please respond asap.

Thanks

Amar pal Singh

**Comment by notoriousbdg** [comment]
You have to enable them in the policy.  Steps 1 and 2 of the installation instructions show how.

**Comment by amar9057** [comment]
Hey !!
Thanks for your reply.
I had already enabled them.However, there are three default policies so I edited all three of them. Any suggestions?

**Comment by amar9057** [comment]
> You have to enable them in the policy. Steps 1 and 2 of the installation instructions show how.

Hey !!
Thanks for your reply.
I had already enabled them.However, there are three default policies so I edited all three of them. Any suggestions?

**Comment by notoriousbdg** [comment]
If you're using a user account that's not an administrator to collect from vCenter, validate the collection user has the permissions documented on https://kb.vmware.com/s/article/53164.

**Comment by amar9057** [comment]
> If you're using a user account that's not an administrator to collect from vCenter, validate the collection user has the permissions documented on https://kb.vmware.com/s/article/53164.

Hey 
Sure. Will check permissions for the collection user and update you soon. Appreciate your time and efforts. 
I work usually from 8:30 PM to 5:30 AM EST and hence w'll update today itself by EON(End of Night).
Thanks

Amar Pal Singh

**Comment by amar9057** [comment]
Hey 

I have made myself a collection user by assigning myself  Global administrator privileges via local admin of vCenters and now along with description and creator fields,the size of the snapshot went field missing as well. Any idea would be more help!!

**Comment by amar9057** [comment]
the size of the snapshot *field went missing as well.

**Comment by notoriousbdg** [comment]
Sorry, I missed your reply.  Are you still having issues?

**Comment by amar9057** [comment]
Thanks for getting back to me. No issues now.

Amar P.
