### ISSUE TITLE
Deleted Snapshots still showing up

### ISSUE THREAD

**Issue by jsakil14** [notoriousbdg/vrops-dashboard-snapshot_detail#7]
Deleted Snapshots still showing up ;

**Comment by bobyuen** [comment]
Yup same problem with me. It's great that I can now see the "Creator" but this snapshot-detail is pulling some old historical data.  So this file is no good until it can be fixed.

Why can't the report check the .vmsd file of the VM. That is the current and real information recorded.

**Comment by notoriousbdg** [comment]
Are the snapshots showing with an age of -1?  If so, that's a known limitation of vROps that can't be worked around.  You can just ignore any of them that show an age of -1.  If that's not the case, can you provide a screenshot?

**Comment by bobyuen** [comment]
Yes, snapshots are show age of -1. and a size with "-" in the report also shows names of former staff members that created them.

Is this known limitation of vROPs documented somewhere?

When you say, ignore it, do mean filter it out in vROPs or just ignore what I see in the PDF report?


[cid:a63b6e30-43af-4188-b27c-711a6eb109e0]


Bob Yuen
Systems Consultant
Information Technology Infrastructure

Simon Fraser University |Water Tower Building
9001 University Crescent
Burnaby, B.C. V5A 4Y8

Phone 778-782-6733
Fax 778-782-4242
Email bobyuen@sfu.ca
www.sfu.ca


________________________________

**Comment by notoriousbdg** [comment]
Unfortunately, there is no way to filter those out.  When you look at the report, you'll have to remember that any of them that have an age of -1 no longer exist.

**Comment by notoriousbdg** [comment]
This issue has been addressed with vROps 8.2 and the latest version of this dashboard.  Please upgrade to vROps 8.2 and update to the latest version of this dashboard.
