### ISSUE TITLE
Old Snapshots being reported. - 

### ISSUE THREAD

**Issue by bobyuen** [notoriousbdg/vrops-dashboard-snapshot_detail#8]
It's great that I can now see the "Creator" but this snapshot-detail is pulling some old historical data. So this file is no good until it can be fixed.

Why can't the report check the .vmsd file of the VM. That is the current and real information recorded.

**Comment by notoriousbdg** [comment]
Are the snapshots showing with an age of -1?  If so, that's a known limitation of vROps that can't be worked around.  You can just ignore any of them that show an age of -1.  If that's not the case, can you provide a screenshot?

**Comment by notoriousbdg** [comment]
This issue has been addressed with vROps 8.2 and the latest version of this dashboard.  Please upgrade to vROps 8.2 and update to the latest version of this dashboard.
